server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fluflu_db
    username: postgres
    password: 12344
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect